<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Products\Meatcut;

class MeatcutSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$meatcut = new Meatcut(["category_id" => "13", "name" => "BOLA DE PIERNA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "BRAZO COMPLETO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "CADERA COMPLETA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "CHATA COMPLETA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "CHOCOZUELA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "COGOTE", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "COLA ENTERA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "COSTILLA COMPLETA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "COSTILLA DELANTERA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "CREADILLA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "DECOMISOS DE RES", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "DESCARGUE COMPLETO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "GRASA DE PECHO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "HUESO CARNUDO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "HUESO DE AGUJA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "HUESO DE PALETA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "HUESO DE PECHO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "HUESO POROSO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "LOMO ENTERO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "MOTA DESPOSTE", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "MURILLO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "PACHAS", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "PECHO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "SEBO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "T BONE", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "TOMAHAWK", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "VIRIL", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "RESERVADO 1", "description" => "no existe aun ", "status" => "0"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "RESERVADO 2", "description" => "no existe aun ", "status" => "0"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "BARRIGA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "BRAZO CERDO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "CABEZA DE CERDO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "CERDO EN CANAL", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "CODO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "COSTILOMO COMPLETO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "DECOMISO DE CERDO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "DORSAL", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "DESPALME", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "EMPELLA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "ESPINAZO DE CERDO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "HUESO POROSO DE CERDO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "MOTA DE CERDO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "PANCETA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "TOCINO PAPADA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "PERNIL", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "PEZUÑA DE CERDO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "RESERVADO 1", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "RESERVADO 2", "description" => "no existe aun ", "status" => "0"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "RESERVADO 3", "description" => "no existe aun ", "status" => "0"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "14", "name" => "RESERVADO 4", "description" => "no existe aun ", "status" => "0"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "15", "name" => "ALAS CON COSTILLAR", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "15", "name" => "ALAS SIN COSTILLAR", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "15", "name" => "DECOMISO DE POLLO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "15", "name" => "MIXTO DE POLLO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "15", "name" => "PECHUGA BLANCA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "15", "name" => "PIERNA PERNIL CON", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "15", "name" => "PIERNA PERNIL SIN", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "15", "name" => "POLLO ENTERO BLANCO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "15", "name" => "POLLO MARINADO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "15", "name" => "RESERVADO 1", "description" => "no existe aun ", "status" => "0"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "BOFE", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "CALLO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "CHUNCHULLO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "CHUNCHULLO PRECOCIDO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "CORAZON", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "DECOMISOS", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "ESPINA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "HIGADO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "LENGUA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "LIBRO Y CUAJO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "PAJARILLA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "PATA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "PULGAREJO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "4", "name" => "ENTRAÑA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "5", "name" => "PRODUCTOS PGC", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "6", "name" => "EMBUTIDOS", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "7", "name" => "OTRAS PROTEINAS", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "8", "name" => "PESCADOS", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "1", "name" => "PIEL DE RES", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "1", "name" => "RES EN CANAL", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "1", "name" => "RES EN PIE", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "1", "name" => "VISCERAS DE RES", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "1", "name" => "VISCERAS DE POLLO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "1", "name" => "CORAZON DE POLLO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "1", "name" => "MENUDENCIA DE POLLO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "1", "name" => "MOLLEJA POLLO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "9", "name" => "SUBPRODUCTOS", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "10", "name" => "TERNERA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "6", "name" => "MOLIPOLLO TRADICIONAL", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "3", "name" => "GALLINA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "11", "name" => "DOMICILIO", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "2", "name" => "NO FABRICADOS", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "1", "name" => "FABRICADOS", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "3", "name" => "HAMBURGUESA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "ROJOS", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "13", "name" => "CARNE DE RES", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "18", "name" => "UVA", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
		$meatcut = new Meatcut(["category_id" => "2", "name" => "CONDIMENTOS", "description" => "no existe aun ", "status" => "1"]);
		$meatcut->save();
	}
}
